import { Inter } from 'next/font/google';
import './globals.css';
import { ReactQueryProvider } from '../lib/react-query-provider';
import { CSPostHogProvider } from './providers';
import StoreProvider from '../state/storeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <CSPostHogProvider>
        <StoreProvider>
          <body className={inter.className}>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </body>
        </StoreProvider>
      </CSPostHogProvider>
    </html>
  );
}
